# Generated by Django 6.1 on 2026-09-14 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectpassport'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmilestone',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
