# Generated by Django 6.1 on 2026-09-15 12:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectmilestone_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('PROGRESS_UPDATE', 'Progress Update'), ('MILESTONE_UPDATE', 'Milestone Update'), ('MATERIAL_DELIVERY', 'Material Delivery'), ('WORK_STARTED', 'Work Started'), ('WORK_COMPLETED', 'Work Completed'), ('ISSUE_REPORTED', 'Issue Reported'), ('GENERAL_UPDATE', 'General Update')], default='GENERAL_UPDATE', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('progress_percentage', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_activities', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='projects.projectmilestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
