# Generated by Django 6.1 on 2026-09-15 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_skill_customerprofile_equipmentownerprofile_and_more'),
        ('projects', '0005_projectactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('unit', models.CharField(max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CostEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estimated_labour_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estimated_other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estimated_total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('ACCEPTED', 'Accepted')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cost_estimates', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_estimates', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimateLabour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workers_required', models.PositiveIntegerField(default=1)),
                ('days_required', models.PositiveIntegerField(default=1)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_items', to='projects.costestimate')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimate_labour_items', to='accounts.skill')),
            ],
        ),
        migrations.CreateModel(
            name='LabourRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(default='day', max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_rates', to='accounts.skill')),
            ],
            options={
                'ordering': ['skill__name'],
            },
        ),
        migrations.CreateModel(
            name='EstimateMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='projects.costestimate')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimate_items', to='projects.materialprice')),
            ],
        ),
    ]
