# Generated by Django 6.1 on 2026-09-15 13:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_skill_customerprofile_equipmentownerprofile_and_more'),
        ('projects', '0006_materialprice_costestimate_estimatelabour_labourrate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, max_length=150)),
                ('name', models.CharField(help_text='Market or location name.', max_length=200)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['county', 'town', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='projectactivity',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectmilestone',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectpassport',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectstatushistory',
            options={},
        ),
        migrations.RemoveField(
            model_name='costestimate',
            name='estimated_labour_cost',
        ),
        migrations.RemoveField(
            model_name='costestimate',
            name='estimated_material_cost',
        ),
        migrations.RemoveField(
            model_name='costestimate',
            name='estimated_other_cost',
        ),
        migrations.RemoveField(
            model_name='costestimate',
            name='estimated_total_cost',
        ),
        migrations.RemoveField(
            model_name='costestimate',
            name='project_area',
        ),
        migrations.RemoveField(
            model_name='projectactivity',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='projectmilestone',
            name='expected_completion_date',
        ),
        migrations.RemoveField(
            model_name='projectmilestone',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='projectpassport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projectstatushistory',
            name='changed_at',
        ),
        migrations.RemoveField(
            model_name='projectstatushistory',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='projectstatushistory',
            name='previous_status',
        ),
        migrations.RemoveField(
            model_name='projectworker',
            name='assigned_at',
        ),
        migrations.AddField(
            model_name='costestimate',
            name='confidence_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Confidence level from 0 to 100.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='costestimate',
            name='estimation_method',
            field=models.CharField(choices=[('RULE_BASED', 'Rule Based'), ('AI', 'Artificial Intelligence'), ('ML', 'Machine Learning'), ('MANUAL', 'Manual')], default='RULE_BASED', max_length=20),
        ),
        migrations.AddField(
            model_name='costestimate',
            name='labour_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='costestimate',
            name='material_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='costestimate',
            name='other_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='costestimate',
            name='price_as_of',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='costestimate',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='estimatelabour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimatematerial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='planned_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='planned_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectpassport',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectstatushistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectstatushistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projectstatushistory',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectworker',
            name='invited_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='costestimate',
            name='name',
            field=models.CharField(default='Construction Cost Estimate', max_length=200),
        ),
        migrations.AlterField(
            model_name='costestimate',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('APPROVED', 'Approved'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='estimatelabour',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estimatelabour',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='estimatematerial',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AlterField(
            model_name='estimatematerial',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='estimatematerial',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projectactivity',
            name='activity_type',
            field=models.CharField(choices=[('PROGRESS_UPDATE', 'Progress Update'), ('MILESTONE_UPDATE', 'Milestone Update'), ('MATERIAL_DELIVERY', 'Material Delivery'), ('WORK_STARTED', 'Work Started'), ('WORK_COMPLETED', 'Work Completed'), ('ISSUE_REPORTED', 'Issue Reported'), ('GENERAL_UPDATE', 'General Update')], max_length=30),
        ),
        migrations.AlterField(
            model_name='projectactivity',
            name='progress_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='projectactivity',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_milestones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DELAYED', 'Delayed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='projectrequiredskill',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectrequiredskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_requirements', to='accounts.skill'),
        ),
        migrations.AlterField(
            model_name='projectstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectworker',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='projects.project'),
        ),
        migrations.CreateModel(
            name='ConstructionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(help_text='Example: Cement, Steel, Timber, Sand, Roofing.', max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('specification', models.CharField(blank=True, help_text='Example: 50kg, 12mm, Grade 500.', max_length=200)),
                ('unit', models.CharField(help_text='Example: bag, kg, tonne, metre, piece, cubic metre.', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'brand', 'specification'), name='unique_construction_material_variant')],
            },
        ),
        migrations.AlterField(
            model_name='estimatematerial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimate_items', to='projects.constructionmaterial'),
        ),
        migrations.CreateModel(
            name='LabourRateObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit', models.CharField(default='day', help_text='Example: day, hour, job.', max_length=50)),
                ('source', models.CharField(choices=[('SUPPLIER', 'Registered Supplier'), ('EXTERNAL', 'External Source'), ('ADMIN', 'Administrator')], max_length=20)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('observed_on', models.DateField()),
                ('is_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_rate_observations', to='accounts.skill')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_labour_rates', to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labour_rate_observations', to='projects.marketlocation')),
            ],
            options={
                'ordering': ['-observed_on', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='estimatelabour',
            name='rate_observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estimate_items', to='projects.labourrateobservation'),
        ),
        migrations.AddField(
            model_name='costestimate',
            name='pricing_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_estimates', to='projects.marketlocation'),
        ),
        migrations.CreateModel(
            name='MaterialPriceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('source', models.CharField(choices=[('SUPPLIER', 'Registered Supplier'), ('EXTERNAL', 'External Source'), ('ADMIN', 'Administrator')], max_length=20)),
                ('source_name', models.CharField(blank=True, help_text='Supplier name, website, API or other source.', max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('observed_on', models.DateField()),
                ('is_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_price_observations', to='projects.marketlocation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_observations', to='projects.constructionmaterial')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_material_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-observed_on', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='estimatematerial',
            name='price_observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estimate_items', to='projects.materialpriceobservation'),
        ),
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_registration_number', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='projects.marketlocation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='materialpriceobservation',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_price_observations', to='projects.supplierprofile'),
        ),
        migrations.AddField(
            model_name='labourrateobservation',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labour_rate_observations', to='projects.supplierprofile'),
        ),
        migrations.DeleteModel(
            name='LabourRate',
        ),
        migrations.DeleteModel(
            name='MaterialPrice',
        ),
        migrations.AddIndex(
            model_name='materialpriceobservation',
            index=models.Index(fields=['material', 'market', 'observed_on'], name='projects_ma_materia_c17d32_idx'),
        ),
        migrations.AddIndex(
            model_name='materialpriceobservation',
            index=models.Index(fields=['source', 'observed_on'], name='projects_ma_source_273854_idx'),
        ),
        migrations.AddIndex(
            model_name='labourrateobservation',
            index=models.Index(fields=['skill', 'market', 'observed_on'], name='projects_la_skill_i_c1868f_idx'),
        ),
        migrations.AddIndex(
            model_name='labourrateobservation',
            index=models.Index(fields=['source', 'observed_on'], name='projects_la_source_d83386_idx'),
        ),
    ]
