# Generated by Django 6.1 on 2026-09-15 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_role_name_supplierprofile'),
        ('projects', '0007_marketlocation_alter_projectactivity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourrateobservation',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labour_rate_observations', to='accounts.supplierprofile'),
        ),
        migrations.AlterField(
            model_name='materialpriceobservation',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_price_observations', to='accounts.supplierprofile'),
        ),
        migrations.DeleteModel(
            name='SupplierProfile',
        ),
    ]
